

# Server
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/Vijayasreepos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=nikhil123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#for images
cloudinary.cloud-name=do3mh63dn
cloudinary.api-key=261159138625881
cloudinary.api-secret=pd8CuMJbigqCa6aPjQr0SKptWyY

# App name
spring.application.name=Vijayasreepos

#JWT Properties
jwt.secret=vijayasreepos-super-secret-key-2026-must-be-32-chars-min
jwt.expiration=86400000

#swagger Documentation
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

