package com.vijayasree.pos.entity;

public enum Permission {
    PRODUCT_VIEW,
    PRODUCT_CREATE,
    PRODUCT_EDIT,
    PRODUCT_DELETE,
    PRODUCT_IMPORT,
    PRODUCT_IMAGE_UPLOAD,
    STOCK_VIEW,
    STOCK_ADJUST,
    STOCK_HISTORY,
    STOCK_PURCHASE,
    SALES_CHECKOUT,
    SALES_APPLY_DISCOUNT,
    REPORTS_DAILY,
    REPORTS_TRANSACTIONS,
    USER_VIEW,
    USER_CREATE,
    USER_EDIT,
    USER_DEACTIVATE,
    USER_GRANT_PERMISSION,
    PRINT_STATION
}